name: Run coverage tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install coverage codecov
      
    - name: Run tests with coverage
      run: |
          coverage run --branch -m unittest discover
          coverage xml
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
          file: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
